on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: R-Generate-Maps

jobs:
  R-Generate-Maps:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          source(here::here('dependencies.R'))
        shell: Rscript {0}
      - name: Generate maps
        run: |
          source(here::here('generate_maps.R'))
        shell: Rscript {0}
